export const mobileTabs = {
  general: {
    title: 'عام',
    fields: [
      'product_name_ar',
      'product_name_en',
      'mobile_availability_date',
      'mobile_company',
      'mobile_company_country',
      'mobile_os',
      'mobile_cellular_networks',
    ],
  },
  design: {
    title: 'التصميم',
    fields: [
      'mobile_dimensions',
      'mobile_weight',
      'mobile_material',
      'mobile_edges',
      'mobile_colors',
      'mobile_waterproof',
      'mobile_dustproof',
    ],
  },
  screen: {
    title: 'الشاشة',
    fields: [
      'mobile_screen_colordepth',
      'mobile_screen_protection',
      'mobile_screen_resolution',
      'mobile_screen_size',
      'mobile_touchscreen_type',
    ],
  },
  sensors: {
    title: 'الحساسات',
    fields: [
      'mobile_fingerprint_reader',
      'mobile_eyeprint_reader',
      'mobile_speed_camera',
      'mobile_barometer',
      'mobile_compass',
    ],
  },
  perfomence: {
    title: 'الأداء',
    fields: [
      'mobile_chipset',
      'mobile_processor',
      'mobile_graphics_chipset',
      'mobile_ram_capacity',
    ],
  },
  camera: {
    title: 'الكاميرا',
    fields: [
      'mobile_front_camera_megapixel',
      'mobile_camera_aperture',
      'mobile_camera_flash_type',
      'mobile_camera_video_resolution',
      'mobile_camera_focusing_mode',
      'mobile_camera_megapixel',
      'mobile_camera_additional_features',
    ],
  },
  storage: {
    title: 'التخزين',
    fields: [
      'mobile_internal_memory_capacity',
      'mobile_external_memory_support',
    ],
  },
  sound: {
    title: 'الصوت',
    fields: [
      'mobile_speakers',
      'mobile_headphone_jack',
      'mobile_microphone_noise_canceling',
    ],
  },
  link: {
    title: 'التوصيل',
    fields: [
      'mobile_sim_card',
      'mobile_dual_sim',
      'mobile_wifi',
      'mobile_bluetooth',
      'mobile_gps',
      'mobile_usb',
      'mobile_nfc',
      'mobile_radio',
    ],
  },
  battery: {
    title: 'البطارية',
    fields: [
      'mobile_battery_capacity',
      'mobile_battery_fast_charging',
      'mobile_battery_playback_time',
      'mobile_battery_removable',
      'mobile_battery_talk_time',
      'mobile_battery_standby_time',
      'mobile_battery_wireless_charging',
    ],
  },
};

export const tabletTabs = {
  general: {
    title: 'عام',
    fields: [
      'product_name_ar',
      'product_name_en',
      'tablet_availability_date',
      'tablet_company',
      'tablet_company_country',
      'tablet_os',
      'tablet_cellular_networks',
    ],
  },
  design: {
    title: 'التصميم',
    fields: [
      'tablet_dimensions',
      'tablet_weight',
      'tablet_material',
      'tablet_edges',
      'tablet_colors',
      'tablet_waterproof',
      'tablet_dustproof',
    ],
  },
  screen: {
    title: 'الشاشة',
    fields: [
      'tablet_screen_colordepth',
      'tablet_screen_protection',
      'tablet_screen_resolution',
      'tablet_screen_size',
      'tablet_touchscreen_type',
    ],
  },
  sensors: {
    title: 'الحساسات',
    fields: [
      'tablet_fingerprint_reader',
      'tablet_eyeprint_reader',
      'tablet_speed_camera',
      'tablet_barometer',
      'tablet_compass',
    ],
  },
  perfomence: {
    title: 'الأداء',
    fields: [
      'tablet_chipset',
      'tablet_processor',
      'tablet_graphics_chipset',
      'tablet_ram_capacity',
    ],
  },
  camera: {
    title: 'الكاميرا',
    fields: [
      'tablet_front_camera_megapixel',
      'tablet_camera_aperture',
      'tablet_camera_flash_type',
      'tablet_camera_video_resolution',
      'tablet_camera_focusing_mode',
      'tablet_camera_megapixel',
      'tablet_camera_additional_features',
    ],
  },
  storage: {
    title: 'التخزين',
    fields: [
      'tablet_internal_memory_capacity',
      'tablet_external_memory_support',
    ],
  },
  sound: {
    title: 'الصوت',
    fields: [
      'tablet_speakers',
      'tablet_headphone_jack',
      'tablet_microphone_noise_canceling',
    ],
  },
  link: {
    title: 'التوصيل',
    fields: [
      'tablet_sim_card',
      'tablet_dual_sim',
      'tablet_wifi',
      'tablet_bluetooth',
      'tablet_gps',
      'tablet_usb',
      'tablet_nfc',
      'tablet_radio',
    ],
  },
  battery: {
    title: 'البطارية',
    fields: [
      'tablet_battery_capacity',
      'tablet_battery_fast_charging',
      'tablet_battery_playback_time',
      'tablet_battery_removable',
      'tablet_battery_talk_time',
      'tablet_battery_standby_time',
      'tablet_battery_wireless_charging',
    ],
  },
};

export const keyToTitle = (key, deviceKey) => {
  const availableTitles = {
    product_name_ar: 'اسم المنتج باللغة العربية',
    product_name_en: 'اسم المنتج باللغة الانجليزية',
    availability_date: 'تاريخ التوفر',
    company: 'الشركة المصنعة',
    company_country: 'منشأ الشركة المصنعة',
    os: 'نظام التشغيل',
    cellular_networks: 'أنواع الشبكات المدعومة',
    dimensions: 'الأبعاد',
    weight: 'الوزن',
    material: 'المادة',
    edges: 'الحواف',
    colors: 'الألوان',
    waterproof: 'ضد الماء',
    dustproof: 'ضد الغبار',
    screen_colordepth: 'عمق ألوان الشاشة',
    screen_protection: 'حماية الشاشة',
    screen_resolution: 'دقة الشاشة',
    screen_size: 'حجم الشاشة',
    touchscreen_type: 'نوع شاشة اللمس',
    fingerprint_reader: 'قارئ البصمة',
    eyeprint_reader: 'قارئ قزحية العين',
    speed_camera: 'حساس السرعه',
    barometer: 'مقياس الضغط الجوى',
    compass: 'البوصلة',
    chipset: 'الشريحة الاساسية',
    processor: 'المعالج',
    graphics_chipset: 'شريحة الرسومات',
    ram_capacity: 'سعة ذاكرة الرام',
    front_camera_megapixel: 'دقة الكاميرا الامامية',
    camera_aperture: 'فتحة العدسة',
    camera_flash_type: 'نوع فلاش الكاميرا',
    camera_video_resolution: 'دقة تصوير الفيديو',
    camera_focusing_mode: 'نوع وضع التركيز',
    camera_megapixel: 'دقة الكاميرا',
    camera_additional_features: 'مميزات إضافية للكاميرا',
    internal_memory_capacity: 'سعة التخزين الداخلية',
    external_memory_support: 'سعة التخزين الخارجية',
    speakers: 'مكبر الصوت',
    headphone_jack: 'منفذ السماعات',
    microphone_noise_canceling: 'إلغاء الضوضاء المحيطية',
    sim_card: 'دعم بطاقات SIM',
    dual_sim: 'دعم بطاقتين SIM',
    wifi: 'الشبكة اللاسلكية (WiFi)',
    bluetooth: 'البلوتوث',
    gps: 'نظام تحديد المواقع',
    usb: 'USB',
    nfc: 'NFC',
    radio: 'راديو',
    battery_capacity: 'سعة البطارية',
    battery_fast_charging: 'دعم الشحن السريع',
    battery_playback_time: 'وقت الإستماع إلى الموسيقى',
    battery_removable: 'قابلية إزالة البطارية',
    battery_talk_time: 'وقت التحدث',
    battery_standby_time: 'وقت الإستعداد',
    battery_wireless_charging: 'دعم الشحن الاسلكى',
  };
  if (key === 'product_name_ar' || key === 'product_name_en') {
    return availableTitles?.[key];
  }
  return availableTitles?.[key.replace(deviceKey, '')] ?? key;
};
